# Generated by Django 5.0.6 on 2024-08-31 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_album_favorite_picture_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='picture',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_pics', to=settings.AUTH_USER_MODEL),
        ),
    ]
